TEMPO_GASTO=0; VELOCIDADE_MEDIA=0; DISTANCIA=0; LITROS_USADOS=0;

TEMPO_GASTO=float(input('Digite o tempo gasto na viagem em horas: '))
VELOCIDADE_MEDIA=float(input('Digite a velocidade médía durante a sua viagem em KM/h: '))

DISTANCIA = TEMPO_GASTO * VELOCIDADE_MEDIA
LITROS_USADOS = DISTANCIA/12

TEMPO_GASTO = str(TEMPO_GASTO)
DISTANCIA = str(DISTANCIA)
LITROS_USADOS = str(LITROS_USADOS)
VELOCIDADE_MEDIA = str(VELOCIDADE_MEDIA)

print('VELOCIDADE MEDIA= '+VELOCIDADE_MEDIA+' KM/h'+'\n'+'TEMPO GASTO= '+TEMPO_GASTO+' h'+'\n'+'DISTANCIA= '+ DISTANCIA+' KM'+'\n'+'LITROS USADOS (12 km/l)= '+LITROS_USADOS)